filebeat.registry.path: /usr/share/filebeat/data/registry

filebeat.config.inputs:
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false

filebeat.modules:
  # OS
  - module: system
    syslog:
      var.paths: ["/var/log/host/system.log*"]
  # Nginx
  - module: nginx
    access:
      var.paths: ["/var/log/nginx/access.log*"]
    error:
      var.paths: ["/var/log/nginx/error.log*"]

monitoring.enabled: true

output.elasticsearch:
  hosts: ["coordinator:9200"]

logging.to_files: false

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true
