filebeat.registry.path: /usr/share/filebeat/data/registry

filebeat.config.inputs:
  path: ${path.config}/prospectors/*.yml
  reload.enabled: false

filebeat.modules:
  # OS
  - module: system
    syslog:
      var.paths: ["/var/log/host/system.log*"]
  # Nginx
  - module: nginx
    access:
      var.paths: ["/var/log/nginx/access.log*"]
    error:
      var.paths: ["/var/log/nginx/error.log*"]

monitoring.enabled: true

output.elasticsearch:
  hosts: ["elc:9200"]

logging.to_files: false

setup:
  kibana.host: "kbn:5601"
  dashboards.enabled: true
