version: '2.2'
services:

  # Coordinator node (elc)
  coordinator:
    container_name: coordinator
    hostname: coordinator
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.master=true
      - node.data=false
      - discovery.seed_hosts=coordinator
      - network.host=coordinator
      - cluster.initial_master_nodes=coordinator
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/coordinator/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      - coorddata:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
    networks:
      - elknet

  # Hot node (elh)
  hot-node:
    container_name: hot-node
    hostname: hot-node
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.master=false
      - node.data=true
      - node.attr.box_type=hot
      - network.host=hot-node
      - discovery.seed_hosts=coordinator
      - cluster.initial_master_nodes=coordinator
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/hot-node/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      - hotdata:/usr/share/elasticsearch/data
    ports: 
      - 9201:9200
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9201/_cat/health"]
    networks:
      - elknet

  # Warm node (elh)
  warm-node:
    container_name: warm-node
    hostname: warm-node
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.master=false
      - node.data=true
      - node.attr.box_type=warm
      - network.host=warm-node
      - discovery.seed_hosts=coordinator
      - cluster.initial_master_nodes=coordinator
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/warm-node/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      - warmdata:/usr/share/elasticsearch/data
    ports: 
      - 9202:9200
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9202/_cat/health"]
    networks:
      - elknet

  # Kibana (kbn)
  kibana:
    container_name: kibana
    hostname: kibana
    image: "docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}"
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_HOSTS: http://coordinator:9200
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elknet
    # depends_on:
    #   coordinator: { condition: service_healthy }
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/"]
      retries: 6

volumes:
  coorddata:
    driver: local
  hotdata:
    driver: local
  warmdata:
    driver: local

networks:
  elknet: