filebeat.registry.path: /usr/share/filebeat/data/registry

filebeat.modules:
  - module: nginx
    access:
      var.paths: ["/var/log/nginx/access.log*"]

monitoring.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

logging.to_files: false

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true